<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	 <TargetFrameworks>netstandard2.0;net10.0</TargetFrameworks>
	<LangVersion>10.0</LangVersion>
	 <IsAotCompatible Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net8.0'))">true</IsAotCompatible>
    <Version>1.0.5</Version>
    <Authors>wombatwebcg</Authors>
    <Company>wombatwebcg</Company>
    <Product>wombatwebcg</Product>
    <Description>Wombat 工业通信蓝牙扩展，提供蓝牙透传 Modbus RTU 能力</Description>
    <PackageTags>plc;modbus;bluetooth;</PackageTags>
    <RepositoryType>git</RepositoryType>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Wombat.IndustrialCommunication\Wombat.IndustrialCommunication.csproj" />
  </ItemGroup>

</Project>
